---
- name: Remove WP-CLI binary installed by Trellis
  file:
    path: "{{ wp_cli_bin_path }}"
    state: absent

- name: Remove WP-CLI bash completion file installed by Trellis
  file:
    path: "{{ wp_cli_completion_path }}"
    state: absent

- name: Remove WP-CLI bundle components via composer
  composer:
    command: remove
    global_command: yes
    arguments: "{{ wp_cli_composer_global_remove_packages | join(' ') }}"
  when: wp_cli_composer_global_remove_packages | length
  become_user: "{{ web_user }}"

- name: Install WP-CLI via composer
  composer:
    command: require
    global_command: yes
    arguments: "{{ wp_cli_composer_global_require_packages | join(' ') }}"
  become_user: "{{ web_user }}"

- name: Install WP-CLI packages
  command: wp package install {{ item }}
  become_user: "{{ web_user }}"
  register: wp_cli_packages_installed
  changed_when:
    - "'Nothing to install or update' not in wp_cli_packages_installed.stdout"
    - "'Package operations: 0 installs, 0 updates, 0 removals' not in wp_cli_packages_installed.stdout"
  with_items: "{{ wp_cli_packages }}"
